import {today} from './domain.js';
export function emptyState(){return {version:1,transactions:[],accounts:[{id:'bank',name:'Main account',kind:'Bank',opening:0},{id:'ewallet',name:'E-wallet',kind:'E-wallet',opening:0},{id:'cash',name:'Cash',kind:'Cash',opening:0}],budgets:{'Food & drinks':60000,'Groceries':50000,'Shopping':40000,'Transport':25000,'Bills & home':160000,'Health & fitness':20000,'Entertainment':15000,'Travel':30000,'Other':20000},goals:[],settings:{name:'',currency:'MYR'}};}
export function demoState(){
 const state=emptyState(),now=today(),month=now.slice(0,7),day=Number(now.slice(8));state.settings.name='Alex';state.accounts[0].name='Everyday account';state.accounts[0].opening=420000;state.accounts[1].name='Touch ’n Go';state.accounts[1].opening=42000;state.accounts[2].opening=25000;
 const merchants=[['Village Park',1850,'Food & drinks','bank'],['Jaya Grocer',12680,'Groceries','bank'],['Grab ride',1640,'Transport','ewallet'],['ZUS Coffee',1290,'Food & drinks','ewallet'],['Uniqlo',14990,'Shopping','bank'],['Fitness membership',15900,'Health & fitness','bank'],['Netflix',5490,'Entertainment','bank'],['Apartment rent',120000,'Bills & home','bank'],['Nasi lemak',850,'Food & drinks','cash'],['Shell',6500,'Transport','bank'],['BookXcess',4290,'Shopping','bank'],['Unifi',12900,'Bills & home','bank'],['Lotus’s',8530,'Groceries','bank'],['Lunch with friends',4200,'Food & drinks','ewallet'],['Spotify',1590,'Entertainment','bank']];
 for(let offset=0;offset<6;offset++){const d=new Date(now+'T12:00:00Z');d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()-offset);const m=d.toISOString().slice(0,7),limit=offset===0?Math.max(day,1):28;
 state.transactions.push({id:`salary-${offset}`,date:m+'-01',merchant:'Monthly salary',amount:580000,type:'income',category:'Salary',account:'bank',source:'Sample data',note:''});
 merchants.forEach(([merchant,amount,category,account],i)=>{state.transactions.push({id:`demo-${offset}-${i}`,date:`${m}-${String(1+(i*7)%limit).padStart(2,'0')}`,merchant,amount:Math.round(amount*(offset===0?1:0.84+offset*0.04)),category,account,type:'expense',source:'Sample data',note:''});});
 if(offset%2===0)state.transactions.push({id:`freelance-${offset}`,date:m+'-01',merchant:'Website project',amount:120000,type:'income',category:'Freelance',account:'bank',source:'Sample data',note:''});}
 state.goals=[{id:'emergency',name:'Emergency fund',target:1500000,saved:825000},{id:'japan',name:'Japan, here we come',target:800000,saved:240000}];return state;
}
