import {spawn} from 'node:child_process';
import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const base=process.env.POCKET_TEST_URL||'http://127.0.0.1:4317/';
const output='.impeccable/review';await mkdir(output,{recursive:true});
const browser=spawn('C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',['--headless=new','--disable-gpu','--in-process-gpu','--no-sandbox','--no-first-run','--no-default-browser-check','--remote-debugging-port=9237','--user-data-dir='+process.cwd()+'/.browser-profile','about:blank'],{windowsHide:true,stdio:['ignore','ignore','pipe']});
let socket;const stderr=[];browser.stderr.on('data',d=>stderr.push(d.toString()));const results=[];
try{
 let targets;for(let i=0;i<80;i++){try{targets=await(await fetch('http://127.0.0.1:9237/json')).json();break;}catch{await delay(150);}}
 assert.ok(targets,'Browser started: '+stderr.join('').slice(-500));socket=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise((r,j)=>{socket.onopen=r;socket.onerror=j;});
 let id=0;const pending=new Map(),errors=[];socket.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);if(p)m.error?p.reject(m.error):p.resolve(m.result);}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text);};
 function send(method,params={}){return new Promise((resolve,reject)=>{const n=++id,timer=setTimeout(()=>reject(Error('CDP timeout: '+method)),90000);pending.set(n,{resolve:r=>{clearTimeout(timer);resolve(r);},reject:e=>{clearTimeout(timer);reject(e);}});socket.send(JSON.stringify({id:n,method,params}));});}
 async function evaluate(expression){const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;}
 async function until(expression){for(let i=0;i<100;i++){if(await evaluate(expression))return;await delay(100);}throw Error('Condition failed: '+expression);}
 const click=selector=>evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);
 async function fill(selector,value){await evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));})()`);}
 const submit=selector=>evaluate(`document.querySelector(${JSON.stringify(selector)}).requestSubmit()`);
 async function navigate(hash){await evaluate(`location.hash=${JSON.stringify(hash)}`);await until(`document.title.startsWith(${JSON.stringify(hash==='budgets'?'Budgets':hash[0].toUpperCase()+hash.slice(1))})`);}
 function pass(name){results.push(name);console.log('PASS '+name);}
 async function capture(name,width,height=1000){await send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:width<760});await delay(250);await evaluate('document.fonts.ready');await evaluate("document.querySelector('#toast').classList.remove('visible');window.scrollTo(0,0)");assert.equal(await evaluate('document.documentElement.scrollWidth>innerWidth'),false,'No page overflow at '+width);const metrics=await send('Page.getLayoutMetrics');const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true,clip:{x:0,y:0,width,height:Math.ceil(metrics.cssContentSize.height),scale:1}});await writeFile(`${output}/${name}.png`,Buffer.from(shot.data,'base64'));}
 await send('Runtime.enable');await send('Page.enable');await send('Page.navigate',{url:base});await until("!!document.querySelector('#quick-form')");await evaluate("localStorage.removeItem('pocket-demo');localStorage.removeItem('pocket-personal');localStorage.removeItem('pocket-mode');location.reload()");await until("!!document.querySelector('#quick-form')");
 assert.equal(await evaluate("document.querySelectorAll('.metric').length"),4);pass('Sample dashboard loads with four metrics and chart');
 await evaluate("document.querySelector('[data-action=month-prev]').focus()");await click('[data-action=month-prev]');assert.equal(await evaluate("document.activeElement.dataset.action"),'month-prev');await click('[data-action=month-next]');await evaluate("document.querySelector('[data-chart=spending]').focus()");await click('[data-chart=spending]');assert.equal(await evaluate("document.activeElement.dataset.chart"),'spending');await click('[data-chart=cashflow]');pass('Keyboard focus survives repeated month and chart changes');
 if(!process.env.POCKET_SKIP_SCREENSHOTS){await capture('desktop',1440);await capture('mobile',390,844);pass('Desktop and mobile screenshots; no page overflow');}
 await evaluate("document.querySelector('#quick-text').focus()");await fill('#quick-text','Coffee RM 12.90 at ZUS yesterday with cash');await submit('#quick-form');await until("document.querySelector('#transaction-form')");assert.equal(await evaluate("document.querySelector('[name=amount]').value"),'12.90');assert.equal(await evaluate("document.querySelector('[name=account]').value"),'cash');await fill('[name=merchant]','Browser test coffee');await submit('#transaction-form');await until("!document.querySelector('#modal').open");assert.equal(await evaluate("JSON.parse(localStorage.getItem('pocket-demo')).transactions.filter(t=>t.merchant==='Browser test coffee').length"),1);pass('Quick capture parses, reviews and saves once');assert.equal(await evaluate('document.activeElement.id'),'quick-text');pass('Saving a transaction restores focus to its original capture field');
 await send('Page.reload');await until("!!document.querySelector('#quick-form')");assert.equal(await evaluate("JSON.parse(localStorage.getItem('pocket-demo')).transactions.filter(t=>t.merchant==='Browser test coffee').length"),1);pass('Transaction survives reload');
 await navigate('transactions');await fill('#transaction-search','Browser test coffee');assert.equal(await evaluate("document.querySelectorAll('tbody tr').length"),1);await click('[data-action=edit-transaction]');await fill('[name=amount]','20.50');await submit('#transaction-form');await until("!document.querySelector('#modal').open");assert.equal(await evaluate("JSON.parse(localStorage.getItem('pocket-demo')).transactions.find(t=>t.merchant==='Browser test coffee').amount"),2050);pass('Search and edit updates persisted amount');
 await click('[data-action=edit-transaction]');await click('[data-action=delete-transaction]');assert.equal(await evaluate("JSON.parse(localStorage.getItem('pocket-demo')).transactions.some(t=>t.merchant==='Browser test coffee')"),false);await click('#toast-action');assert.equal(await evaluate("JSON.parse(localStorage.getItem('pocket-demo')).transactions.some(t=>t.merchant==='Browser test coffee')"),true);pass('Delete with undo restores original transaction');
 await navigate('budgets');await click('[data-action=edit-budget]');await fill('[name=amount]','750');await submit('#budget-form');await until("!document.querySelector('#modal').open");assert.equal(await evaluate("JSON.parse(localStorage.getItem('pocket-demo')).budgets['Food & drinks']"),75000);pass('Budget edit persists');
 await click('[data-action=new-goal]');await fill('[name=name]','Test adventure');await fill('[name=target]','5000');await fill('[name=saved]','250');await submit('#goal-form');await until("!document.querySelector('#modal').open");assert.equal(await evaluate("JSON.parse(localStorage.getItem('pocket-demo')).goals.find(g=>g.name==='Test adventure').saved"),25000);pass('Savings goal creation persists');
 await navigate('accounts');await click('[data-action=new-account]');await fill('[name=name]','Test debt');await fill('[name=kind]','Loan');await fill('[name=opening]','-1000');await submit('#account-form');await until("!document.querySelector('#modal').open");assert.equal(await evaluate("JSON.parse(localStorage.getItem('pocket-demo')).accounts.find(a=>a.name==='Test debt').opening"),-100000);pass('Debt account supports a negative opening balance');
 await navigate('overview');await click('[data-action=start-personal]');assert.equal(await evaluate("document.querySelectorAll('tbody tr').length"),0);pass('Personal workspace starts clean, separate from demo');
 await click('[data-action=capture]');await click('[data-action=manual]');await fill('[name=merchant]','<img src=x onerror=alert(1)>');await fill('[name=amount]','5');await submit('#transaction-form');await until("!document.querySelector('#modal').open");assert.equal(await evaluate("document.querySelectorAll('td img').length"),0);assert.equal(await evaluate("JSON.parse(localStorage.getItem('pocket-personal')).transactions.length"),1);pass('User content is escaped, not interpreted as HTML');
 await click('[data-action=capture]');await click('[data-action=manual]');await fill('[name=merchant]','Transfer');await fill('[name=amount]','10');await click('[name=type][value=transfer]');await fill('[name=account]','bank');await fill('[name=toAccount]','bank');await submit('#transaction-form');assert.equal(await evaluate("document.querySelector('#modal').open"),true);assert.match(await evaluate("document.querySelector('#form-error').textContent"),/different account/);await click('[data-action=close]');pass('Invalid same-account transfers are blocked with recovery message');
 await navigate('transactions');await click('[data-action=import-csv]');await evaluate(`(()=>{const dt=new DataTransfer();dt.items.add(new File([['date,merchant,amount,type,category,account',''].join(String.fromCharCode(10))+new Date().toISOString().slice(0,10)+',CSV lunch,18.50,expense,Food & drinks,cash'], 'statement.csv',{type:'text/csv'}));const input=document.querySelector('#csv-file');input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}));})()`);await until("!!document.querySelector('#confirm-import')");assert.match(await evaluate("document.querySelector('#confirm-import').textContent"),/Import 1/);await click('#confirm-import');assert.equal(await evaluate("JSON.parse(localStorage.getItem('pocket-personal')).transactions.length"),2);pass('CSV upload previews and imports valid transactions');
 await navigate('settings');await fill('[name=name]','Jamie');await submit('#settings-form');assert.equal(await evaluate("document.querySelector('#profile-name').textContent"),'Jamie');await click('[data-action=switch-demo]');await until("!!document.querySelector('#quick-form')");assert.equal(await evaluate("document.querySelector('#profile-name').textContent"),'Alex');pass('Preferences persist independently per workspace');
 await click('[data-action=voice]');assert.equal(await evaluate("!!document.querySelector('#voice-transcript')"),true);await fill('#voice-transcript','Lunch RM 15 with cash');await click('#voice-review');assert.equal(await evaluate("document.querySelector('[name=amount]').value"),'15.00');await click('[data-action=close]');pass('Voice transcript is editable and uses the review flow');
 await click('[data-action=receipt]');assert.equal(await evaluate("!!document.querySelector('.dropzone')"),true);await click('[data-action=close]');pass('Receipt capture offers upload, camera and manual recovery');
 for(const width of [320,768,1024,1920]){await send('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:width<760});assert.equal(await evaluate('document.documentElement.scrollWidth>innerWidth'),false,'No overflow at '+width);}pass('Layout stays within 320, 768, 1024 and 1920 pixel widths');
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});for(const route of ['transactions','budgets','accounts','settings']){await navigate(route);assert.equal(await evaluate('document.documentElement.scrollWidth>innerWidth'),false,'No mobile overflow on '+route);}pass('All five views fit mobile');
 await navigate('overview');await click('[data-action=capture]');await send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await send('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});assert.equal(await evaluate("document.querySelector('#modal').open"),false);pass('Dialog supports Escape dismissal');
 const unlabeled=await evaluate("Array.from(document.querySelectorAll('button')).filter(b=>!b.textContent.trim()&&!b.getAttribute('aria-label')&&!b.title).length");assert.equal(unlabeled,0);pass('All buttons have accessible names');
 assert.deepEqual(errors,[]);pass('No unhandled browser exceptions');
 await writeFile(`${output}/browser-results.json`,JSON.stringify({passed:results.length,results,errors},null,2));console.log(`${results.length} browser checks passed.`);
}finally{if(socket?.readyState===1){try{socket.send(JSON.stringify({id:999999,method:'Browser.close'}));}catch{}socket.close();}browser.kill();browser.stderr.destroy();}
