import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {openBrowser,delay} from './browser-tools.js';
const b=await openBrowser({profile:'interactions'}),results=[];
async function check(name,run){try{await b.reset();await run();results.push({name,passed:true});console.log('PASS '+name);}catch(error){results.push({name,passed:false,error:error.message});console.log('FAIL '+name+': '+error.message);}}
async function manual(){await b.click('[data-action=capture]');await b.click('[data-action=manual]');await b.fill('[name=merchant]','Repeated click transaction');await b.fill('[name=amount]','12.50');}
try{
 await check('Quick draft survives chart, month and route navigation',async()=>{
  await b.fill('#quick-text','Lunch RM 18 with cash');await b.pointerClick('[data-chart=spending]');assert.equal(await b.evaluate("document.querySelector('#quick-text').value"),'Lunch RM 18 with cash');
  await b.pointerClick('[data-action=month-prev]');await b.route('accounts');await b.route('overview');assert.equal(await b.evaluate("document.querySelector('#quick-text').value"),'Lunch RM 18 with cash');
 });
 await check('Settings draft survives repeated navigation clicks',async()=>{await b.route('settings');await b.fill('[name=name]','Draft name');await b.pointerClick('#navigation [data-view=settings]');assert.equal(await b.evaluate("document.querySelector('[name=name]').value"),'Draft name');});
 await check('Capture tabs preserve typed text and edited voice transcripts',async()=>{await b.click('[data-action=capture]');await b.fill('#capture-text','Coffee RM 15');await b.pointerClick('[data-capture-tab=voice]');await b.fill('#voice-transcript','Lunch RM 20');await b.pointerClick('[data-capture-tab=text]');assert.equal(await b.evaluate("document.querySelector('#capture-text').value"),'Coffee RM 15');await b.pointerClick('[data-capture-tab=voice]');assert.equal(await b.evaluate("document.querySelector('#voice-transcript').value"),'Lunch RM 20');});
 await check('Rapid repeated submissions create exactly one record',async()=>{await manual();await b.evaluate("(()=>{const f=document.querySelector('#transaction-form');for(let i=0;i<5;i++)f.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));})()");assert.equal(await b.evaluate("JSON.parse(localStorage.getItem('pocket-demo')).transactions.filter(t=>t.merchant==='Repeated click transaction').length"),1);});
 await check('Pagination retains usable keyboard focus',async()=>{await b.evaluate(`(async()=>{const s=(await import('./seed.js')).demoState();s.transactions.push(...s.transactions.slice(0,16).map(t=>({...t,id:t.id+'-extra'})));const text=JSON.stringify(s);localStorage.setItem('pocket-demo',text);dispatchEvent(new StorageEvent('storage',{key:'pocket-demo',newValue:text}));})()`);await b.route('transactions');assert.equal(await b.evaluate("document.querySelector('[data-action=page-next]').disabled"),false);await b.evaluate("document.querySelector('[data-action=page-next]').focus()");await b.click('[data-action=page-next]');assert.equal(await b.evaluate("document.activeElement.dataset.action==='page-next'||document.activeElement.dataset.action==='page-prev'"),true);});
 await check('Closing CSV import discards a delayed file result',async()=>{
  await b.click('[data-action=capture]');await b.click('[data-action=close]');await b.route('transactions');await b.click('[data-action=import-csv]');
  await b.evaluate(`(()=>{window.oldFileText=File.prototype.text;File.prototype.text=function(){return new Promise(resolve=>window.finishCSV=()=>resolve('date,merchant,amount\\n2026-10-02,Delayed import,15'))};const dt=new DataTransfer();dt.items.add(new File(['x'],'slow.csv',{type:'text/csv'}));const input=document.querySelector('#csv-file');input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  await b.click('[data-action=close]');await b.evaluate('window.finishCSV()');await delay(100);assert.equal(await b.evaluate("document.querySelector('#modal').open"),false);
 });
 await check('Delayed restore cannot cross workspace boundaries',async()=>{
  await b.route('settings');await b.evaluate(`(()=>{File.prototype.text=function(){return new Promise(resolve=>window.finishBackup=()=>resolve(JSON.stringify(window.backupFixture)))};})()`);
  await b.evaluate(`(async()=>{window.backupFixture=(await import('./seed.js')).demoState();const dt=new DataTransfer();dt.items.add(new File(['x'],'slow.json',{type:'application/json'}));const input=document.querySelector('#backup-file');input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  await b.click('[data-action=start-personal]');await b.evaluate('window.finishBackup()');await delay(100);assert.equal(await b.evaluate("document.querySelector('#modal').open"),false);assert.equal(await b.evaluate("document.querySelectorAll('tbody tr').length"),0);
 });
 await check('An edited transaction cannot overwrite a newer tab update',async()=>{
  await b.route('transactions');await b.click('[data-action=edit-transaction]');await b.fill('[name=amount]','20.00');
  await b.evaluate(`(async()=>{const s=JSON.parse(localStorage.getItem('pocket-demo'))||(await import('./seed.js')).demoState();const id=document.querySelector('#transaction-form').dataset.id;s.transactions.find(t=>t.id===id).amount=3300;const text=JSON.stringify(s);localStorage.setItem('pocket-demo',text);dispatchEvent(new StorageEvent('storage',{key:'pocket-demo',newValue:text}));})()`);
  await b.evaluate("document.querySelector('#transaction-form').requestSubmit()");assert.equal(await b.evaluate("document.querySelector('#modal').open"),true);assert.match(await b.evaluate("document.querySelector('#form-error').textContent"),/changed|another tab/i);
 });
 await check('Invalid month values cannot crash navigation',async()=>{await b.evaluate("const e=document.querySelector('#selected-month');e.value='0001-01';e.dispatchEvent(new Event('change',{bubbles:true}));document.querySelector('[data-action=month-prev]').click()");assert.equal(await b.evaluate("!!document.querySelector('#quick-form')"),true);assert.match(await b.evaluate("document.querySelector('#selected-month').value"),/^\d{4}-\d{2}$/);});
 await check('Skip to content keeps the current route',async()=>{await b.route('transactions');await b.click('.skip-link');await delay(50);assert.equal(await b.evaluate('location.hash'),'#transactions');assert.equal(await b.evaluate('document.activeElement.id'),'main');});
 await check('Follow-up under an older answer uses that answer',async()=>{
  await b.route('assistant');for(const question of ['Food spending this month','Transport spending this month']){await b.fill('#assistant-input',question);await b.evaluate("document.querySelector('#assistant-form').requestSubmit()");await b.until("!document.querySelector('.assistant-thinking')");}
  await b.click('.assistant-turn:first-child .answer-followups button');await b.until("document.querySelectorAll('.assistant-turn').length===3&&!document.querySelector('.assistant-thinking')");assert.match(await b.evaluate("document.querySelector('.assistant-turn:last-child .answer-scope').textContent"),/Food & drinks/);
 });
 await check('Opening an evidence editor resets dictation state',async()=>{
  await b.route('assistant');await b.fill('#assistant-input','Show expenses');await b.evaluate("document.querySelector('#assistant-form').requestSubmit()");await b.until("!!document.querySelector('[data-ask-record]')");
  await b.evaluate("window.SpeechRecognition=class{start(){}abort(){}};document.querySelector('.assistant-evidence').open=true");await b.click('[data-ask-voice]');await b.click('[data-ask-record]');await b.click('[data-action=close]');assert.equal(await b.evaluate("document.querySelector('[data-ask-voice]').getAttribute('aria-label')"),'Dictate your question');
 });
 await check('Storage failure preserves the form and retry saves once',async()=>{
  await manual();await b.evaluate("window.savedSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw new DOMException('Full','QuotaExceededError')};document.querySelector('#transaction-form').requestSubmit()");assert.match(await b.evaluate("document.querySelector('#form-error').textContent"),/storage is full/i);assert.equal(await b.evaluate("document.querySelector('[name=amount]').value"),'12.50');await b.evaluate("Storage.prototype.setItem=window.savedSetItem;document.querySelector('#transaction-form').requestSubmit()");assert.equal(await b.evaluate("JSON.parse(localStorage.getItem('pocket-demo')).transactions.filter(t=>t.merchant==='Repeated click transaction').length"),1);
 });
 await check('Export, backup, template and file-picker controls are wired',async()=>{
  await b.evaluate("window.downloads=[];window.pickers=[];HTMLAnchorElement.prototype.click=function(){window.downloads.push({name:this.download,url:this.href})};HTMLInputElement.prototype.click=function(){if(this.type==='file')window.pickers.push(this.id)}");
  await b.route('transactions');await b.pointerClick('[data-action=export-csv]');await b.pointerClick('[data-action=import-csv]');await b.pointerClick('[data-action=csv-template]');await b.pointerClick('[data-action=choose-csv]');await b.click('[data-action=close]');await b.route('settings');await b.pointerClick('[data-action=backup]');await b.pointerClick('[data-action=export-all]');await b.pointerClick('[data-action=restore]');
  const files=await b.evaluate('window.downloads');assert.equal(files.length,4);assert.ok(files.every(f=>f.url.startsWith('blob:')));assert.deepEqual(await b.evaluate('window.pickers'),['csv-file','backup-file']);
  await b.route('overview');await b.pointerClick('[data-action=camera]');await b.pointerClick('[data-action=choose-receipt]');assert.deepEqual(await b.evaluate('window.pickers.slice(-2)'),['camera-file','receipt-file']);await b.click('[data-action=close]');
 });
 await check('Restore confirmation replaces only the selected workspace',async()=>{
  await b.route('settings');await b.evaluate(`(async()=>{const s=(await import('./seed.js')).emptyState();s.settings.name='Restored';s.accounts[0].opening=4200;const dt=new DataTransfer();dt.items.add(new File([JSON.stringify(s)],'pocket.json',{type:'application/json'}));const input=document.querySelector('#backup-file');input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}));})()`);await b.until("!!document.querySelector('#confirm-restore')");await b.pointerClick('#confirm-restore');assert.equal(await b.evaluate("JSON.parse(localStorage.getItem('pocket-demo')).settings.name"),'Restored');assert.equal(await b.evaluate("localStorage.getItem('pocket-personal')"),null);assert.equal(await b.evaluate("document.querySelector('#modal').open"),false);
 });
 await check('Goal deletion, undo and account editing update exactly once',async()=>{
  await b.route('budgets');await b.pointerClick('[data-action=edit-goal]');await b.pointerClick('[data-action=delete-goal]');assert.equal(await b.evaluate("JSON.parse(localStorage.getItem('pocket-demo')).goals.length"),1);await b.pointerClick('#toast-action');assert.equal(await b.evaluate("JSON.parse(localStorage.getItem('pocket-demo')).goals.length"),2);
  await b.route('accounts');await b.pointerClick('[data-action=edit-account]');await b.fill('[name=name]','Renamed account');await b.fill('[name=opening]','125.50');await b.evaluate("document.querySelector('#account-form').requestSubmit()");assert.equal(await b.evaluate("JSON.parse(localStorage.getItem('pocket-demo')).accounts[0].opening"),12550);assert.match(await b.evaluate("document.querySelector('.account-card').textContent"),/Renamed account/);
 });
 await check('Capture keyboard tabs and Escape return focus to the opener',async()=>{
  await b.pointerClick('[data-action=capture]');await b.evaluate("document.querySelector('[data-capture-tab=text]').focus()");await b.send('Input.dispatchKeyEvent',{type:'keyDown',key:'ArrowRight',code:'ArrowRight',windowsVirtualKeyCode:39});assert.equal(await b.evaluate('document.activeElement.dataset.captureTab'),'voice');await b.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});assert.equal(await b.evaluate("document.querySelector('#modal').open"),false);assert.equal(await b.evaluate('document.activeElement.dataset.action'),'capture');
 });
 await check('Slow AI capture ignores repeated submits and stale errors after cancel',async()=>{
  await b.send('Page.addScriptToEvaluateOnNewDocument',{source:`window.aiRequests=0;const originalFetch=window.fetch;window.fetch=async(url,options)=>{if(String(url).includes('/api/capabilities'))return new Response('{"ai":true}',{headers:{'Content-Type':'application/json'}});if(String(url).includes('/api/extract')){window.aiRequests++;return new Promise((resolve,reject)=>{window.rejectCapture=()=>reject(Error('Old request failed'));options.signal.addEventListener('abort',()=>reject(new DOMException('Cancelled','AbortError')),{once:true});});}return originalFetch(url,options);}`});
  await b.send('Page.reload');await b.until("!!document.querySelector('#quick-form')");await b.click('[data-action=capture]');await b.until("!!document.querySelector('#use-ai')");await b.fill('#capture-text','Coffee RM 20');await b.click('#use-ai');await b.evaluate("const form=document.querySelector('#text-capture-form');for(let i=0;i<5;i++)form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}))");assert.equal(await b.evaluate('window.aiRequests'),1);
  await b.click('[data-action=close]');await manual();await b.evaluate('window.rejectCapture()');await delay(80);assert.equal(await b.evaluate("document.querySelector('#form-error').textContent"),'');assert.equal(await b.evaluate("document.querySelector('[name=merchant]').value"),'Repeated click transaction');
 });
 assert.deepEqual(b.errors,[],'No uncaught browser errors');
}catch(error){results.push({name:'No uncaught browser errors',passed:false,error:error.message});}
finally{await mkdir('.impeccable/review/optimization',{recursive:true});await writeFile('.impeccable/review/optimization/interactions.json',JSON.stringify({passed:results.filter(r=>r.passed).length,results,errors:b.errors},null,2));await b.close();}
console.log(`${results.filter(r=>r.passed).length}/${results.length} interaction checks passed.`);if(results.some(r=>!r.passed))process.exitCode=1;
